from pony.orm import *
from datetime import datetime

db = Database('sqlite', 'players.sqlite', create_db=True)
pony.options.MAX_FETCH_COUNT=50000

class Players(db.Entity):
    _table_ = "profile_stats"

    id = PrimaryKey(int, auto=True)
    last_updated = Required(datetime)
    name = Required(unicode, 50)
    server = Optional(unicode, 25)
    profile_string = Required(unicode, 30)
    captures = Required(int)
    disconnects = Required(int)
    drops = Required(int)
    games = Required(int)
    grabs = Required(int)
    hold = Required(int)
    hours = Required(float)
    losses = Required(int)
    non_return_tags = Required(int)
    popped = Required(int)
    prevent = Required(int)
    returns = Required(int)
    support = Required(int)
    tags = Required(int)
    wins = Required(int)

    captures_per_hour = Optional(float)
    disconnects_per_hour = Optional(float)
    drops_per_hour = Optional(float)
    games_per_hour = Optional(float)
    grabs_per_hour = Optional(float)
    hold_per_hour = Optional(float)
    losses_per_hour = Optional(float)
    non_return_tags_per_hour = Optional(float)
    popped_per_hour = Optional(float)
    prevent_per_hour = Optional(float)
    returns_per_hour = Optional(float)
    support_per_hour = Optional(float)
    tags_per_hour = Optional(float)
    wins_per_hour = Optional(float)

    captures_per_game = Optional(float)
    disconnects_per_game = Optional(float)
    drops_per_game = Optional(float)
    grabs_per_game = Optional(float)
    hold_per_game = Optional(float)
    losses_per_game = Optional(float)
    non_return_tags_per_game = Optional(float)
    popped_per_game = Optional(float)
    prevent_per_game = Optional(float)
    returns_per_game = Optional(float)
    support_per_game = Optional(float)
    tags_per_game = Optional(float)
    wins_per_game = Optional(float)

    ranks = Optional("Ranks")
    monthly = Optional("Monthly")
    weekly = Optional("Weekly")
    daily = Optional("Daily")


class Ranks(db.Entity):
    player_id = Required(Players)
    captures = Optional(int)
    disconnects = Optional(int)
    drops = Optional(int)
    games = Optional(int)
    grabs = Optional(int)
    hold = Optional(int)
    hours = Optional(int)
    losses = Optional(int)
    non_return_tags = Optional(int)
    popped = Optional(int)
    prevent = Optional(int)
    returns = Optional(int)
    support = Optional(int)
    tags = Optional(int)
    wins = Optional(int)

class Monthly(db.Entity):
    player = Required(Players)
    captures = Required(int)
    disconnects = Required(int)
    drops = Required(int)
    games = Required(int)
    grabs = Required(int)
    hold = Required(int)
    hours = Required(float)
    losses = Required(int)
    popped = Required(int)
    prevent = Required(int)
    returns = Required(int)
    support = Required(int)
    tags = Required(int)
    wins = Required(int)

    captures_per_hour = Optional(float)
    disconnects_per_hour = Optional(float)
    drops_per_hour = Optional(float)
    games_per_hour = Optional(float)
    grabs_per_hour = Optional(float)
    hold_per_hour = Optional(float)
    losses_per_hour = Optional(float)
    non_return_tags_per_hour = Optional(float)
    popped_per_hour = Optional(float)
    prevent_per_hour = Optional(float)
    returns_per_hour = Optional(float)
    support_per_hour = Optional(float)
    tags_per_hour = Optional(float)
    wins_per_hour = Optional(float)

    captures_per_game = Optional(float)
    disconnects_per_game = Optional(float)
    drops_per_game = Optional(float)
    grabs_per_game = Optional(float)
    hold_per_game = Optional(float)
    losses_per_game = Optional(float)
    non_return_tags_per_game = Optional(float)
    popped_per_game = Optional(float)
    prevent_per_game = Optional(float)
    returns_per_game = Optional(float)
    support_per_game = Optional(float)
    tags_per_game = Optional(float)
    wins_per_game = Optional(float)

class Weekly(db.Entity):
    player = Required(Players)
    captures = Required(int)
    disconnects = Required(int)
    drops = Required(int)
    games = Required(int)
    grabs = Required(int)
    hold = Required(int)
    hours = Required(float)
    losses = Required(int)
    popped = Required(int)
    prevent = Required(int)
    returns = Required(int)
    support = Required(int)
    tags = Required(int)
    wins = Required(int)

    captures_per_hour = Optional(float)
    disconnects_per_hour = Optional(float)
    drops_per_hour = Optional(float)
    games_per_hour = Optional(float)
    grabs_per_hour = Optional(float)
    hold_per_hour = Optional(float)
    losses_per_hour = Optional(float)
    non_return_tags_per_hour = Optional(float)
    popped_per_hour = Optional(float)
    prevent_per_hour = Optional(float)
    returns_per_hour = Optional(float)
    support_per_hour = Optional(float)
    tags_per_hour = Optional(float)
    wins_per_hour = Optional(float)

    captures_per_game = Optional(float)
    disconnects_per_game = Optional(float)
    drops_per_game = Optional(float)
    grabs_per_game = Optional(float)
    hold_per_game = Optional(float)
    losses_per_game = Optional(float)
    non_return_tags_per_game = Optional(float)
    popped_per_game = Optional(float)
    prevent_per_game = Optional(float)
    returns_per_game = Optional(float)
    support_per_game = Optional(float)
    tags_per_game = Optional(float)
    wins_per_game = Optional(float)

class Daily(db.Entity):
    player = Required(Players)
    captures = Required(int)
    disconnects = Required(int)
    drops = Required(int)
    games = Required(int)
    grabs = Required(int)
    hold = Required(int)
    hours = Required(float)
    losses = Required(int)
    popped = Required(int)
    prevent = Required(int)
    returns = Required(int)
    support = Required(int)
    tags = Required(int)
    wins = Required(int)

    captures_per_hour = Optional(float)
    disconnects_per_hour = Optional(float)
    drops_per_hour = Optional(float)
    games_per_hour = Optional(float)
    grabs_per_hour = Optional(float)
    hold_per_hour = Optional(float)
    losses_per_hour = Optional(float)
    non_return_tags_per_hour = Optional(float)
    popped_per_hour = Optional(float)
    prevent_per_hour = Optional(float)
    returns_per_hour = Optional(float)
    support_per_hour = Optional(float)
    tags_per_hour = Optional(float)
    wins_per_hour = Optional(float)

    captures_per_game = Optional(float)
    disconnects_per_game = Optional(float)
    drops_per_game = Optional(float)
    grabs_per_game = Optional(float)
    hold_per_game = Optional(float)
    losses_per_game = Optional(float)
    non_return_tags_per_game = Optional(float)
    popped_per_game = Optional(float)
    prevent_per_game = Optional(float)
    returns_per_game = Optional(float)
    support_per_game = Optional(float)
    tags_per_game = Optional(float)
    wins_per_game = Optional(float)

db.generate_mapping(create_tables=True)
